# This file is a template, and might need editing before it works on your project.
# Official docker image.
services:
  - docker:stable-dind

stages:
  - build
  - deploy

variables:
  CI_REGISTRY: "docker.io"
  CI_REGISTRY_IMAGE: "beardedio/terraria"
  CI_REGISTRY_USER: "set-as-secret-variable"
  CI_REGISTRY_PASSWORD: "set-as-secret-variable"

build:
  stage: build
  image: docker:stable
  only:
    - master
    - schedules
  variables:
    FOLDER: "tshock"
  before_script:
    - apk add --no-cache curl
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - ./bin/build-all

deploy:
  image: ilyasemenov/gitlab-ci-git-push
  variables:
    SSH_PRIVATE_KEY: "set-as-secret-variable"
  stage: deploy
  only:
    - master
  script: git-push git@github.com:beardedio/terraria.git refs/heads/master
